"""Replication-package archival job (paper Data Availability section).

Zips each run family with an INTERNAL per-file SHA-256 manifest, writes the ZIP checksums to
`archives/MANIFEST.sha256` (COMMITTED), and stages the zips under `archives/` (NOT committed;
gitignored via `archives/*.zip`). The author copies the zips off-machine and verifies them
against MANIFEST.sha256. Run traces stay local per the `runs/*` .gitignore convention; this job
is the off-machine bridge that the Data Availability section points at.

Families:
  matrix_1b : runs/matrix_1b                               (confirmatory experiment)
  pilot     : run dirs resolved from analysis/matrix_manifest.json (the pilot cell set)
  a7        : runs/a7                                       (benign-noise smoke)

Determinism note: zip mtimes make the ZIP bytes non-reproducible run-to-run, so MANIFEST.sha256
records THIS snapshot's ZIP checksums; the internal per-file manifest is the content-stable record.
"""
import json, os, sys, hashlib, zipfile
from pathlib import Path

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, REPO)
RUNS = os.path.join(REPO, "runs")
ARCH = os.path.join(REPO, "archives")


def sha256_file(p):
    h = hashlib.sha256()
    with open(p, "rb") as f:
        for b in iter(lambda: f.read(1 << 20), b""):
            h.update(b)
    return h.hexdigest()


def walk_files(dirs):
    out = []
    for d in dirs:
        if not os.path.isdir(d):
            continue
        for root, _, files in os.walk(d):
            out.extend(os.path.join(root, fn) for fn in files)
    return sorted(out)


def pilot_dirs():
    """The pilot run dirs = the committed pilot manifest cells resolved to their run dirs."""
    from analysis.gates import cell_run_dir
    cells = json.load(open(os.path.join(REPO, "analysis", "matrix_manifest.json"), encoding="utf-8"))
    dirs, seen, missing = [], set(), 0
    for c in cells:
        d = cell_run_dir(Path(RUNS), c)
        if d is None:
            missing += 1
        elif str(d) not in seen:
            seen.add(str(d)); dirs.append(str(d))
    return dirs, len(cells), missing


def family_zip(name, dirs):
    files = walk_files(dirs)
    manifest = "\n".join(f"{sha256_file(f)}  {os.path.relpath(f, RUNS)}" for f in files)
    zpath = os.path.join(ARCH, f"{name}.zip")
    with zipfile.ZipFile(zpath, "w", zipfile.ZIP_DEFLATED) as z:
        for f in files:
            z.write(f, arcname=os.path.relpath(f, REPO))
        z.writestr(f"MANIFEST_{name}.sha256", manifest + "\n")
    return {"zip": f"{name}.zip", "sha256": sha256_file(zpath),
            "n_dirs": len(dirs), "n_files": len(files),
            "size_bytes": os.path.getsize(zpath)}


def main():
    os.makedirs(ARCH, exist_ok=True)
    fam = {}
    fam["matrix_1b"] = family_zip("matrix_1b", [os.path.join(RUNS, "matrix_1b")])
    pdirs, ncells, missing = pilot_dirs()
    fam["pilot"] = family_zip("pilot", pdirs)
    fam["pilot"].update(manifest_cells=ncells, cells_missing_dir=missing)
    fam["a7"] = family_zip("a7", [os.path.join(RUNS, "a7")])

    lines = [
        "# Replication-package archive checksums (SHA-256 of each ZIP).",
        "# Zips are staged under archives/ (gitignored) for off-machine copy; verify with:",
        "#   cd archives && sha256sum -c MANIFEST.sha256",
        "# Generated by analysis/archive_replication.py over local runs/ (traces stay local",
        "# per the runs/* .gitignore convention). Each ZIP also carries an internal",
        "# MANIFEST_<family>.sha256 with per-file checksums.",
        "",
    ]
    for k in ("matrix_1b", "pilot", "a7"):
        f = fam[k]
        extra = (f"   (pilot = {f['manifest_cells']} manifest cells resolved; "
                 f"{f['cells_missing_dir']} had no run dir)") if k == "pilot" else ""
        lines.append(f"{f['sha256']}  {f['zip']}")
        lines.append(f"#   {k}: {f['n_dirs']} run dirs, {f['n_files']} files, "
                     f"{f['size_bytes']} bytes{extra}")
    open(os.path.join(ARCH, "MANIFEST.sha256"), "w", encoding="utf-8").write("\n".join(lines) + "\n")
    print("\n".join(lines))


if __name__ == "__main__":
    main()
