"""`make freeze`: generate prereg.md — protocol Sections 6.1, 6.2, 6.4
verbatim — pinned (M6 amendment 3, per the D2-era custody ruling) with:
the FROZEN-materials commit hash, the four frozen-artifact sha256s, the CLI
version, and the deviations.md reference. prereg.md carries the -text
attribute (byte-stable checkouts) since the FROZEN commit."""
from __future__ import annotations

import hashlib
import subprocess
import sys
from datetime import date
from pathlib import Path
from typing import Optional

REPO_ROOT = Path(__file__).resolve().parent.parent
PROTOCOL = REPO_ROOT / "pilot_protocol.md"
PREREG = REPO_ROOT / "prereg.md"
FROZEN_FILES = ("sentinel/dsl.py", "prompts/sentinel_compile.md",
                "prompts/sentinel_judge.md", "prompts/worker.md")


def extract_section(text: str, start: str, stops: tuple[str, ...]) -> str:
    lines = text.splitlines()
    begin = next(i for i, line in enumerate(lines) if line.startswith(start))
    end = len(lines)
    for i in range(begin + 1, len(lines)):
        if any(lines[i].startswith(stop) for stop in stops):
            end = i
            break
    return "\n".join(lines[begin:end]).rstrip()


def sha256_file(rel_path: str) -> str:
    return hashlib.sha256((REPO_ROOT / rel_path).read_bytes()).hexdigest()


def frozen_commit_hash() -> str:
    out = subprocess.run(
        ["git", "log", "--reverse", "--format=%H", "--", "sentinel/dsl.py"],
        cwd=REPO_ROOT, capture_output=True, text=True, check=True)
    return out.stdout.split()[0]


def build_prereg() -> str:
    from conductor.sessions import get_cli_version
    protocol_text = PROTOCOL.read_text(encoding="utf-8")
    s61 = extract_section(protocol_text, "### 6.1", ("### 6.2",))
    s62 = extract_section(protocol_text, "### 6.2", ("### 6.3",))
    s64 = extract_section(protocol_text, "### 6.4", ("---", "## 7"))
    pins = "\n".join(
        f"  {sha256_file(path)}  {path}" for path in FROZEN_FILES)
    return f"""# Pre-registration (frozen copy, generated by `make freeze`)

Frozen on {date.today().isoformat()}, before any Phase 1 run. The kill gates
below were written by the person you are today; the person staring at a
near-miss table in late July does not get a vote.

## Custody pins

- FROZEN-materials commit: {frozen_commit_hash()}
- Frozen-artifact sha256 (working tree at freeze time; byte-stable via
  .gitattributes -text):
{pins}
- Claude Code CLI version: {get_cli_version()}
- Methodology deviations: see `deviations.md` (D1-D15), an inseparable part
  of this pre-registration record; sha256 at freeze time:
  {sha256_file('deviations.md')}

---

{s61}

---

{s62}

---

{s64}
"""


def main(argv: Optional[list[str]] = None) -> int:
    PREREG.write_text(build_prereg(), encoding="utf-8")
    print(f"wrote {PREREG} — commit it (Definition of Done)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
